FROM python:3.6.8

WORKDIR /opt/app

RUN apt-get update && apt-get -y install chrpath

RUN pip install pipenv

COPY Pipfile /opt/app
COPY Pipfile.lock /opt/app

RUN pipenv install

COPY . /opt/app

RUN pipenv run nuitka3 --lto main.py --recurse-all --standalone --remove-output

CMD ["./main.dist/main", "console"]
